name: Тестовый запуск
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare config
        run: |
          cat > connection_config.ini <<EOT
          [testit]
          url = https://172.16.251.133
          privateToken = ${{ secrets.TMS_PRIVATE_TOKEN }}
          projectId = eefe44b2-3347-4e63-83e6-18614e869fe3
          configurationId = 659d9644-c5dc-4542-8aef-3858f219f8b6
          testRunId =
          testRunName = Test
          adapterMode = 2
          EOT

      - name: Test run for testit
        env:
          PYTHONWARNINGS: "ignore:Unverified HTTPS request"
        run: |
          pytest_output=$(pytest tests/test_projects.py --testit 2>&1)
          echo "pytest_output=$pytest_output" >> $GITHUB_ENV
          if [[ "$pytest_output" == *"INTERNALERROR"* ]]; then
            echo "An internal error occurred during test execution. Please check the output above for details."
            exit 1
          fi
